# Generated by Django 3.0.2 on 2020-01-11 10:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('session', '0004_auto_20200111_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source_id', models.CharField(editable=False, max_length=33)),
                ('game_id', models.CharField(choices=[('dua_empat', 'Dua Empat')], max_length=16)),
            ],
            options={
                'db_table': 'play',
            },
        ),
        migrations.AddConstraint(
            model_name='play',
            constraint=models.UniqueConstraint(fields=('source_id',), name='play_has_unique_source_id'),
        ),
    ]
