# Generated by Django 3.0 on 2019-12-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(editable=False, max_length=33, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('picture', models.URLField(max_length=128)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
