# Generated by Django 3.0 on 2019-12-15 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_id', models.CharField(editable=False, max_length=33)),
            ],
            options={
                'db_table': 'line_account',
            },
        ),
        migrations.AddConstraint(
            model_name='lineaccount',
            constraint=models.UniqueConstraint(fields=('line_id',), name='line_account_has_unique_line_id'),
        ),
    ]
