# Generated by Django 3.0 on 2019-12-29 00:51

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = []
