# Generated by Django 3.0 on 2019-12-29 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WerewolfPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(editable=False, max_length=33)),
                ('is_alive', models.BooleanField(default=True)),
                ('role',
                 models.CharField(choices=[('v', 'Penduduk'), ('w', 'Werewolf'), ('s', 'Peramal'), ('d', 'Dokter')],
                                  default='v', max_length=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'db_table': 'werewolf_player',
            },
        ),
        migrations.AddConstraint(
            model_name='werewolfplayer',
            constraint=models.UniqueConstraint(fields=('source_id', 'profile'),
                                               name='werewolf_player_has_unique_source_id_profile'),
        ),
    ]
