# Generated by Django 3.0.2 on 2020-01-11 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0003_auto_20200111_1523'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='score',
            table='score',
        ),
    ]
