# Generated by Django 3.0.2 on 2020-01-11 09:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_number', models.IntegerField(default=0)),
                ('second_number', models.IntegerField(default=0)),
                ('third_number', models.IntegerField(default=0)),
                ('fourth_number', models.IntegerField(default=0)),
                ('source_id', models.CharField(editable=False, max_length=33)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('source_id',), name='question_has_unique_source_id'),
        ),
    ]
